spring.datasource.url=jdbc:postgresql://localhost:5432/authorization_example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Cokolsuper12

spring.jpa.hibernate:ddl-auto:update
spring.application.name=authorization_example
